#!/usr/bin/env bash

set -e

main() {
	echo "Installing Sublime Text 3"

	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
	apt-add-repository "deb https://download.sublimetext.com/ apt/stable/"
	apt-get update && apt-get install sublime-text
}

main
